### ISSUE TITLE
Search broken on server side

### ISSUE THREAD

**Issue by eliasmalik** [tbtommyb/concertspot#12]
I get a 500 internal server error:

<img width="322" alt="screen shot 2017-01-07 at 09 49 57" src="https://cloud.githubusercontent.com/assets/12719553/21740877/da51e0a4-d4be-11e6-8c69-9bc0b89a58b4.png">

<img width="462" alt="screen shot 2017-01-07 at 09 50 09" src="https://cloud.githubusercontent.com/assets/12719553/21740878/dc8e1eaa-d4be-11e6-9284-2dd13dc839dd.png">

<img width="196" alt="screen shot 2017-01-07 at 09 50 19" src="https://cloud.githubusercontent.com/assets/12719553/21740879/dedbb46a-d4be-11e6-9e24-5d0ca5267ab6.png">

**Comment by tbtommyb** [comment]
Fixed now (but not finding anything for Nao, I'm afraid)
