### ISSUE TITLE
Static directory listing error

### ISSUE THREAD

**Issue by eliasmalik** [tbtommyb/concertspot#14]
Visit https://www.concertspot.co.uk/static/

Looks like some webpack error that I shouldn't be able to see. 

On a related note, is there any reason to have the directory listing config option set to true?

**Comment by tbtommyb** [comment]
On the second point, are you referring to webpack or nginx config?

**Comment by eliasmalik** [comment]
I meant [this](https://github.com/tbtommyb/concertspot/blob/master/src/backend/server/routes.js#L22). This route now seems to be forbidden by nginx, so I guess it doesn't matter anymore.

**Comment by tbtommyb** [comment]
Ah good spot. I have fixed in Hapi too.
